version: '3.8'
services:
  api-server:
    container_name: app-isamm
    build: .
    command: npm run dev
    ports:
      - "8080:3000"
    links:
      - postgre_db
    depends_on:
      - postgre_db
    volumes:
      - ./:/usr/app/
      - /usr/app/node_modules


  postgre_db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data


  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"