version: '3.9'
services:
  art_server:
    container_name: art_server
    build: .
    command: npm run dev
    ports:
      - "8080:3000"
    links:
      - postgre_db
    depends_on:
      - postgre_db
    volumes:
      - ./:/usr/app/
      - /usr/app/node_modules

  postgre_db:
    container_name: postgre_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  pg_admin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"

volumes:
  data:
