version: "2"
services:
  app-isamm:
    container_name: app-isamm
    build: .
    command: npm run dev
    ports:
      - "8080:3000"
    links:
      - db-isamm
    depends_on:
      - db-isamm
    volumes:
      - ./:/usr/app/
      - /usr/app/node_modules
    

  db-isamm:
    container_name: db-isamm
    image: mongo
    volumes:
      - mongo:/data/db
    ports:
      - '27018:27017'

  postgres:
    image: postgres
    ports:
      - "8081:8081"
    restart: always
    links:
      - db-isamm
    environment:
      POSTGRES_PASSWORD: example

